import sys

import numpy as np
from pandas.core.base import NoNewAttributesMixin as NoNewAttributesMixin
from pandas.core.indexes.base import Index
from pandas.core.series import Series
from pandas.core.frame import DataFrame
from typing import Any, List, Optional, Union, overload

if sys.version_info >= (3, 8):
    from typing import Literal
else:
    from typing_extensions import Literal

ExportOrientationList = Literal['records']

def cat_core(list_of_columns: List[np.ndarray], sep: str) -> Any: ...
def cat_safe(list_of_columns: List[np.ndarray], sep: str) -> Any: ...
def str_count(arr: Any, pat: Any, flags: int = ...) -> Any: ...
def str_contains(arr: Any, pat: Any, case: bool = ..., flags: int = ..., na: Any = ..., regex: bool = ...) -> Any: ...
def str_startswith(arr: Any, pat: Any, na: Any = ...) -> Any: ...
def str_endswith(arr: Any, pat: Any, na: Any = ...) -> Any: ...
def str_replace(arr: Any, pat: Any, repl: Any, n: int = ..., case: Optional[Any] = ..., flags: int = ..., regex: bool = ...) -> Any: ...
def str_repeat(arr: Any, repeats: Any) -> Any: ...
def str_match(arr: Any, pat: Any, case: bool = ..., flags: int = ..., na: Any = ...) -> Any: ...
def str_extract(arr: Any, pat: Any, flags: int = ..., expand: bool = ...) -> Any: ...
def str_extractall(arr: Any, pat: Any, flags: int = ...) -> Any: ...
def str_get_dummies(arr: Any, sep: str = ...) -> Any: ...
def str_join(arr: Any, sep: Any) -> Any: ...
def str_findall(arr: Any, pat: Any, flags: int = ...) -> Any: ...
def str_find(arr: Any, sub: Any, start: int = ..., end: Optional[Any] = ..., side: str = ...) -> Any: ...
def str_index(arr: Any, sub: Any, start: int = ..., end: Optional[Any] = ..., side: str = ...) -> Any: ...
def str_pad(arr: Any, width: Any, side: str = ..., fillchar: str = ...) -> Any: ...
def str_split(arr: Any, pat: Optional[Any] = ..., n: Optional[Any] = ...) -> Any: ...
def str_rsplit(arr: Any, pat: Optional[Any] = ..., n: Optional[Any] = ...) -> Any: ...
def str_slice(arr: Any, start: Optional[Any] = ..., stop: Optional[Any] = ..., step: Optional[Any] = ...) -> Any: ...
def str_slice_replace(arr: Any, start: Optional[Any] = ..., stop: Optional[Any] = ..., repl: Optional[Any] = ...) -> Any: ...
def str_strip(arr: Any, to_strip: Optional[Any] = ..., side: str = ...) -> Any: ...
def str_wrap(arr: Any, width: Any, **kwargs: Any) -> Any: ...
def str_translate(arr: Any, table: Any) -> Any: ...
def str_get(arr: Any, i: Any) -> Any: ...
def str_decode(arr: Any, encoding: Any, errors: str = ...) -> Any: ...
def str_encode(arr: Any, encoding: Any, errors: str = ...) -> Any: ...
def forbid_nonstring_types(forbidden: Any, name: Optional[Any] = ...) -> Any: ...
def copy(source: Any) -> Any: ...

class StringMethods(NoNewAttributesMixin):
    def __init__(self, data: Any) -> None: ...
    def __getitem__(self, key: Any) -> Series: ...
    def __iter__(self) -> Any: ...
    @overload
    def cat(self, others: None = ..., sep: Optional[Any] = ..., na_rep: Optional[Any] = ..., join: str = ...) -> str: ...
    @overload
    def cat(self, others: Optional[Any] = ..., sep: Optional[Any] = ..., na_rep: Optional[Any] = ..., join: str = ...) -> Series: ...
    @overload
    def split(self, pat: Optional[Any] = ..., n: int = ..., expand: Literal[False] = ...) -> Series: ...
    @overload
    def split(self, pat: Optional[Any] = ..., n: int = ..., expand: Literal[True] = ...) -> DataFrame: ...
    @overload
    def rsplit(self, pat: Optional[Any] = ..., n: int = ..., expand: Literal[False] = ...) -> Series: ...
    @overload
    def rsplit(self, pat: Optional[Any] = ..., n: int = ..., expand: Literal[True] = ...) -> DataFrame: ...
    @overload
    def partition(self, sep: str = ..., expand: Literal[False] = ...) -> Series: ...
    @overload
    def partition(self, sep: str = ..., expand: Literal[True] = ...) -> DataFrame: ...
    @overload
    def rpartition(self, sep: str = ..., expand: Literal[False] = ...) -> Series: ...
    @overload
    def rpartition(self, sep: str = ..., expand: Literal[True] = ...) -> DataFrame: ...
    def get(self, i: Any) -> Series: ...
    def join(self, sep: Any) -> Series: ...
    def contains(self, pat: Any, case: bool = ..., flags: int = ..., na: Any = ..., regex: bool = ...) -> Series: ...
    def match(self, pat: Any, case: bool = ..., flags: int = ..., na: Any = ...) -> Series: ...
    def replace(self, pat: Any, repl: Any, n: int = ..., case: Optional[Any] = ..., flags: int = ..., regex: bool = ...) -> Series: ...
    def repeat(self, repeats: Any) -> Series: ...
    def pad(self, width: Any, side: str = ..., fillchar: str = ...) -> Series: ...
    def center(self, width: Any, fillchar: str = ...) -> Series: ...
    def ljust(self, width: Any, fillchar: str = ...) -> Series: ...
    def rjust(self, width: Any, fillchar: str = ...) -> Series: ...
    def zfill(self, width: Any) -> Series: ...
    def slice(self, start: Optional[Any] = ..., stop: Optional[Any] = ..., step: Optional[Any] = ...) -> Series: ...
    def slice_replace(self, start: Optional[Any] = ..., stop: Optional[Any] = ..., repl: Optional[Any] = ...) -> Series: ...
    def decode(self, encoding: Any, errors: str = ...) -> Series: ...
    def encode(self, encoding: Any, errors: str = ...) -> Series: ...
    def strip(self, to_strip: Optional[str] = ...) -> Series: ...
    def lstrip(self, to_strip: Optional[str] = ...) -> Series: ...
    def rstrip(self, to_strip: Optional[str] = ...) -> Series: ...
    def wrap(self, width: Any, **kwargs: Any) -> Series: ...
    def get_dummies(self, sep: str = ...) -> DataFrame: ...
    def translate(self, table: Any) -> Series: ...
    def count(self, pat: str, flags: int = ...)-> Series: ...
    def startswith(self, pat: str, na: Optional = ...) -> Series: ...
    def endswith(self, pat: str, na: Optional = ...) -> Series: ...
    def extract(self, pat: Any, flags: int = ..., expand: bool = ...) -> Union[DataFrame, Series]: ...
    def extractall(self, pat: Any, flags: int = ...) -> DataFrame: ...
    def findall(self, pat: Any, flags: int = ...) -> DataFrame: ...
    def find(self, sub: Any, start: int = ..., end: Optional[Any] = ...) -> Series: ...
    def rfind(self, sub: Any, start: int = ..., end: Optional[Any] = ...) -> Series: ...
    def normalize(self, form: Any) -> Any: ...
    def index(self, sub: Any, start: int = ..., end: Optional[Any] = ...) -> Series: ...
    def rindex(self, sub: Any, start: int = ..., end: Optional[Any] = ...) -> Series: ...
    def len(self) -> Series: ...
    def lower(self) -> Series: ...
    def upper(self) -> Series: ...
    def title(self) -> Series: ...
    def capitalize(self) -> Series: ...
    def swapcase(self) -> Series: ...
    def casefold(self) -> Series: ...
    def isalnum(self) -> Series: ...
    def isalpha(self) -> Series: ...
    def isdigit(self) -> Series: ...
    def isspace(self) -> Series: ...
    def islower(self) -> Series: ...
    def isupper(self) -> Series: ...
    def istitle(self) -> Series: ...
    def isnumeric(self) -> Series: ...
    def isdecimal(self) -> Series: ...
